### PR TITLE
[FEATURE] add getMatchingCountry

### PR DESCRIPTION
**Pull request by guiliuri13**
Exported the function to get the country code by number.

### CODE REVIEW

**Comment by AstrOOnauta** [comment]
Hey @guiliuri13, Thanks for your PR!

I revised your PR and...there are interesting commits!

**1. [FEATURE] add getMatchingCountry (HASH 1c4ac026c3e71cfcd5415444177c4405d9c8d57b):**
   - This is a good commit! :)
   - But you need to improve the typescript to the function getMatchingCountry in declare file. The correct would be:
   ```
	export declare function getMatchingCountry(phoneNumber: string): ICountry | undefined;
   ```
   - The rest is okay!

**2. [CONFIG] auth infos (HASH 057abac324b1d077ef51efd5690306aaced28614):**
   - Bad Commit :C

**3. [FIX] name pattern (HASH 88e2dea985ceaa24e893f55fdbddd8d8d3dae8c0):**
   - Bad Commit :C

**4. [FIX] fix exports (HASH a8fb6eab5fa829cd446d415648e2b4b96c3e7822):**
   - This is a good commit! :)
   - In file `lib/index.js` you must not export getMatchingCountry and phoneMask like this (in your commit):
     ```
	export { getMatchingCountry } from "./utils/getMatchingCountry"
	export { phoneMask } from "./utils/inputMask"
     ```
     As you did is redundant, because both have already been imported from the appropriate path at the beginning of the file. So, export only as follows:
     ```
     export { getMatchingCountry, phoneMask}
     ```
   - And you need to improve the typescript to the function getMatchingCountry in declare file, too. The correct would be:
   ```
	export declare function phoneMask(value: string, countryCode?: string): string;
   ```
   - The rest is okay!


So, could you re-PR this, without the bad commit and with the required adjustments?

🚀AstrOOnauta 🚀

**Comment by AstrOOnauta** [comment]
Hey @guiliuri13, Thanks for your PR!

I revised your PR and...there are interesting commits!

**1. [FEATURE] add getMatchingCountry (HASH 1c4ac026c3e71cfcd5415444177c4405d9c8d57b):**
   - This is a good commit! :)
   - But you need to improve the typescript to the function getMatchingCountry in declare file. The correct would be:
   ```
	export declare function getMatchingCountry(phoneNumber: string): ICountry | undefined;
   ```
   - The rest is okay!

**2. [CONFIG] auth infos (HASH 057abac324b1d077ef51efd5690306aaced28614):**
   - Bad Commit :C

**3. [FIX] name pattern (HASH 88e2dea985ceaa24e893f55fdbddd8d8d3dae8c0):**
   - Bad Commit :C

**4. [FIX] fix exports (HASH a8fb6eab5fa829cd446d415648e2b4b96c3e7822):**
   - This is a good commit! :)
   - In file `lib/index.js` you must not export getMatchingCountry and phoneMask like this (in your commit):
     ```
	export { getMatchingCountry } from "./utils/getMatchingCountry"
	export { phoneMask } from "./utils/inputMask"
     ```
     As you did is redundant, because both have already been imported from the appropriate path at the beginning of the file. So, export only as follows:
     ```
     export { getMatchingCountry, phoneMask}
     ```
   - And you need to improve the typescript to the function getMatchingCountry in declare file, too. The correct would be:
     ```
	export declare function phoneMask(value: string, countryCode?: string): string;
     ```
   - The rest is okay!


So, could you re-PR this, without the bad commit and with the required adjustments?

🚀AstrOOnauta 🚀

**Comment by AstrOOnauta** [comment]
Hey @guiliuri13, Thanks for your PR!

I revised your PR and...there are interesting commits!

**1. [FEATURE] add getMatchingCountry (HASH 1c4ac026c3e71cfcd5415444177c4405d9c8d57b):**
   - This is a good commit! :)
   - But you need to improve the typescript to the function getMatchingCountry in declare file. The correct would be:
   ```
	export declare function getMatchingCountry(phoneNumber: string): ICountry | undefined;
   ```
   - The rest is okay!

**2. [CONFIG] auth infos (HASH 057abac324b1d077ef51efd5690306aaced28614):**
   - Bad Commit :C

**3. [FIX] name pattern (HASH 88e2dea985ceaa24e893f55fdbddd8d8d3dae8c0):**
   - Bad Commit :C

**4. [FIX] fix exports (HASH a8fb6eab5fa829cd446d415648e2b4b96c3e7822):**
   - This is a good commit! :)
   - In file `lib/index.js` you must not export getMatchingCountry and phoneMask like this (in your commit):
   ```
	export { getMatchingCountry } from "./utils/getMatchingCountry"
	export { phoneMask } from "./utils/inputMask"
   ```
     
   As you did is redundant, because both have already been imported from the appropriate path at the beginning of the file. So, export only as follows:
   ```
     export { getMatchingCountry, phoneMask}
   ```
     
   - And you need to improve the typescript to the function getMatchingCountry in declare file, too. The correct would be:
   ```
	export declare function phoneMask(value: string, countryCode?: string): string;
   ```
     
   - The rest is okay!


So, could you re-PR this, without the bad commit and with the required adjustments?

🚀AstrOOnauta 🚀

**Comment by guiliuri13** [comment]
> 

Of course, I'll tidy up your notes and make another pull request as soon as possible. I still hope to modify a good part of the architecture, hence the fork. I will always keep you with the credits! Thanks

**Pull request closed without merging**
